# ---------- Build Stage ----------
FROM node:16-alpine AS build

WORKDIR /app
RUN apk add --no-cache git

RUN git clone https://github.com/pelthepu/todo-ui.git .

# No hardcoded URL
ENV REACT_APP_API_URL=/api

RUN npm install --legacy-peer-deps
RUN npm run build


# ---------- Runtime Stage ----------
FROM nginx:alpine

# Copy build
COPY --from=build /app/build /usr/share/nginx/html

# Copy custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]