FROM maven:3.8.6-openjdk-11-slim AS build
WORKDIR /app
RUN apt-get update && apt-get install -y git --no-install-recommends
RUN git clone https://github.com/pelthepu/todo-api.git .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:11-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]